name: Build Custom RustDesk APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c # Versão estável para RustDesk

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.0'


      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Injetar Configurações
        run: |
          CONF="flutter/lib/common.dart"
          sed -i "s|const RENDEZVOUS_SERVER = .*|const RENDEZVOUS_SERVER = '${{ secrets.MY_ID_SERVER }}';|" $CONF
          sed -i "s|const RELAY_SERVER = .*|const RELAY_SERVER = '${{ secrets.MY_RELAY_SERVER }}';|" $CONF
          sed -i "s|const RS_PUB_KEY = .*|const RS_PUB_KEY = '${{ secrets.MY_PUB_KEY }}';|" $CONF
          sed -i "s|bool checkUpdate = .*|bool checkUpdate = false;|" $CONF
          sed -i "s|bool stopUpgrade = .*|bool stopUpgrade = true;|" $CONF

      - name: Install Essential Build Tools
        run: |
          sudo apt-get update
          # Instalamos apenas o essencial para compilação cruzada (cross-compilation)
          sudo apt-get install -y g++-multilib cmake python3-pip

      - name: Build APK ARM64
        run: |
          # 1. Configura variáveis de ambiente
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          
          # 2. Prepara o Rust para Android
          rustup target add aarch64-linux-android
          
          # 3. Entra na pasta e limpa dependências
          cd flutter
          flutter pub get
          
          # 4. Executa o build focando APENAS em Android ARM64
          # O parâmetro --no-pub evita que ele tente baixar coisas durante o build
          flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-1.4.7-Custom
          path: flutter/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
